name: CI-CD

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}
      
      - name: Build and push Docker images
        uses: docker/build-push-action@v3.0.0
        with:
          file: ./src/Dockerfile
          context: ./src/
          push: true
          tags: |
            ewertonmarschalk/kube-news:latest
            ewertonmarschalk/kube-news:${{github.run_number}}
            

            
          
